### ISSUE TITLE
Disk read benchmark fails if "foo.txt" is not present

### ISSUE THREAD

**Issue by lupino3** [sirupsen/napkin-math#6]
Sorry if I just report instead of fixing, a bit short of time right now and I am absolutely not familiar with Rust.

I installed Rust and cloned the repo, but when I try to run the benchmark (`cargo run --release`) I get the following errors:

```
    Finished release [optimized] target(s) in 2m 23s
     Running `target\release\base-rates.exe`

[Read Seq Vec<usize>] Iterations in 100 miliseconds, no overhead: 134,217,727
[Read Seq Vec<usize>] Iterations / second: 1,342,177,270
[Read Seq Vec<usize>] Bytes handled per iteration: 8 bytes
[Read Seq Vec<usize>] Total bytes processed: 1024.000 MiB
[Read Seq Vec<usize>] Throughput: 10.000 GiB/s
[Read Seq Vec<usize>] Avg single iteration: 0.752 ns
[Read Seq Vec<usize>] Avg single iteration cycles: 2.71
[Read Seq Vec<usize>] Time to process 1 MiB: 98 μs
[Read Seq Vec<usize>] Time to process 1 GiB: 100 ms
[Read Seq Vec<usize>] Time to process 1 TiB: 103.31 s

[Write Seq Vec<usize>] Iterations in 5655 miliseconds, no overhead: 538,076,672
[Write Seq Vec<usize>] Iterations / second: 95,150,605
[Write Seq Vec<usize>] Bytes handled per iteration: 8 bytes
[Write Seq Vec<usize>] Total bytes processed: 4.009 GiB
[Write Seq Vec<usize>] Throughput: 725.942 MiB/s
[Write Seq Vec<usize>] Avg single iteration: 10.510 ns
[Write Seq Vec<usize>] Avg single iteration cycles: 37.84
[Write Seq Vec<usize>] Time to process 1 MiB: 1377 μs
[Write Seq Vec<usize>] Time to process 1 GiB: 1410 ms
[Write Seq Vec<usize>] Time to process 1 TiB: 24.07 min

[Random Read Vec<usize>] Iterations in 4028 miliseconds, no overhead: 134,217,727
[Random Read Vec<usize>] Iterations / second: 33,321,183
[Random Read Vec<usize>] Bytes handled per iteration: 8 bytes
[Random Read Vec<usize>] Total bytes processed: 1024.000 MiB
[Random Read Vec<usize>] Throughput: 254.220 MiB/s
[Random Read Vec<usize>] Avg single iteration: 30 ns
[Random Read Vec<usize>] Avg single iteration cycles: 108.04
[Random Read Vec<usize>] Time to process 1 MiB: 3933 μs
[Random Read Vec<usize>] Time to process 1 GiB: 4.03 s
[Random Read Vec<usize>] Time to process 1 TiB: 1.15 hours

[Real: Random Write Vec<usize>] Iterations in 5006 miliseconds, no overhead: 475,077,717
[Real: Random Write Vec<usize>] Iterations / second: 94,901,661
[Real: Random Write Vec<usize>] Bytes handled per iteration: 8 bytes
[Real: Random Write Vec<usize>] Total bytes processed: 3.540 GiB
[Real: Random Write Vec<usize>] Throughput: 724.042 MiB/s
[Real: Random Write Vec<usize>] Avg single iteration: 10.539 ns
[Real: Random Write Vec<usize>] Avg single iteration cycles: 37.94
[Real: Random Write Vec<usize>] Time to process 1 MiB: 1381 μs
[Real: Random Write Vec<usize>] Time to process 1 GiB: 1414 ms
[Real: Random Write Vec<usize>] Time to process 1 TiB: 24.13 min
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:1084:5note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: process didn't exit successfully: `target\release\base-rates.exe` (exit code: 101)
```

With `RUST_BACKTRACE=1` I get the following (not very helpful IMHO) backtrace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:1084:5stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.34\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:477
   6: std::panicking::continue_panic_fmt
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:384
   7: std::panicking::rust_begin_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:311
   8: core::panicking::panic_fmt
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libcore\panicking.rs:85
   9: core::result::unwrap_failed
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libcore\result.rs:1084
  10: alloc::alloc::box_free
  11: alloc::alloc::box_free
  12: <T as core::any::Any>::type_id
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:49
  14: std::panicking::try::do_call<closure-0,i32>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:296
  15: panic_unwind::__rust_maybe_catch_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libpanic_unwind\lib.rs:80
  16: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:275
  17: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panic.rs:394
  18: std::rt::lang_start_internal
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:48
  19: main
  20: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  21: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  22: BaseThreadInitThunk
  23: RtlUserThreadStart
error: process didn't exit successfully: `target\release\base-rates.exe` (exit code: 101)
```

The directory does not have a file called `foo.txt`. If I create it, then the benchmark is able to execute this test.

**Comment by sirupsen** [comment]
Hm strange, this seems to be a Windows-only bug. The file should be opened with `create(true)` 🤔

**Comment by lupino3** [comment]
Yes, sorry, forgot to mention. This is under windows. (I don't remember if I was using WSL when I filed the bug but I think it was under PowerShell Core (no WSL).

**Comment by sirupsen** [comment]
should be fixed now, although windows is no longer supported 🙃
